# Generated by Django on 2026-06-01

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_contest_fields(apps, schema_editor):
    Contest = apps.get_model('contests', 'Contest')

    for contest in Contest.objects.all():
        updates = []

        if contest.end_time is None:
            contest.end_time = contest.start_time + timedelta(
                minutes=contest.duration_minutes or 0
            )
            updates.append('end_time')

        if not contest.slug:
            base_slug = slugify(contest.title) or f'contest-{contest.pk}'
            slug = base_slug
            suffix = 1
            while Contest.objects.filter(slug=slug).exclude(pk=contest.pk).exists():
                slug = f'{base_slug}-{suffix}'
                suffix += 1
            contest.slug = slug
            updates.append('slug')

        if updates:
            contest.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('snapshot_type', models.CharField(choices=[('live', 'Live'), ('freeze', 'Freeze'), ('final', 'Final')], default='live', max_length=10)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='contests.contest')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='contest',
            name='contests_co_is_publ_7b2f4e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contestregistration',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='contestproblem',
            old_name='label',
            new_name='order_label',
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='order_label',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'order_label'), ('contest', 'problem')},
        ),
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ['order_label']},
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='freeze_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_contest_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('ICPC', 'ICPC'), ('IOI', 'IOI'), ('CF', 'Codeforces')], default='ICPC', max_length=10),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='contestregistration',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='contestregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contestregistration',
            unique_together={('user', 'contest')},
        ),
        migrations.RemoveField(
            model_name='contest',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_rated',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='order',
        ),
    ]
