# Generated by Django 6.0.5 on 2026-06-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_scoreboardsnapshot_alter_contestproblem_options_and_more'),
        ('submissions', '0003_failedsubmission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_user_id_7ddccf_idx',
            old_name='submissions_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_status_c2b4f2_idx',
            old_name='submissions_status_d4e5f6_idx',
        ),
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_after_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
